tests: test pip install plugin with less dependencies
This was done in order to avoid conda/mamba issues showing up like:

```
RemoveError: 'requests' is a dependency of conda and cannot be removed from conda's operating environment.
```